title: ''
logo: 'logo.svg'
author:
  name: Webmaster                           # Default author name
  email: 'webmaster@opennms.org'            # Default author email
  copyright: "Copyright 2016 The OpenNMS Group, Inc. All Rights Reserved."
social:
  - url: 'https://github.com/OpenNMS'
    icon: 'github'
    description: 'Fork us on GitHub'
  - url: 'https://twitter.com/opennms/'
    icon: 'twitter'
    description: 'Follow us on Twitter'
  - url: 'https://www.youtube.com/user/opennms'
    icon: 'youtube'
    description: 'Show me videos about OpenNMS on YouTube'
  - url: 'https://plus.google.com/105624063334939417498'
    icon: 'google-plus'
    description: 'Follow us on Google Plus'
  - url: 'stay-informed.rss'
    icon: 'rss'
    description: 'Subscribe news as RSS feed'
  - url: 'https://www.facebook.com/OpenNMS/'
    icon: 'facebook'
    description: 'Follow on Facebook'
  - url: 'http://chat.opennms.com/opennms'
    icon: 'comments-o'
    description: 'Talk with people in the community'

contact:
  address:
    - line: "220 Chatham Business Drive"
    - line: "Pittsboro, North Carolina 27312"
    - line: "United States"
othermenu:
  - text: "About"
    url: "about"
  - text: "Privacy Policy"
    url: "privacy-policy"
  - text: "Trademark Policy"
    url: "trademark-policy"
  - text: "Contact"
    url: "contact"
quicklinks:
  - text: "OpenNMS"
    url: "base_url:opennms"
  - text: "Participate"
    url: "base_url:participate"
  - text: "Blog"
    url: "base_url:blog"
  - text: "Code of Conduct"
    url: "base_url:code-of-conduct"

taxonomies: [category,tag]                  # Arbitrary list of taxonomy types
blog:
  route: '/blog'                            # Route to blog
metadata:
    description: 'Project home page of OpenNMS - a java based network managememnt platform developed under the Open Source model'
summary:
  size: 300                                 # Maximum length of summary (characters)

header_options:
  arrows: 'true'                            # Create Next and previous button
  autoslide: 'false'                        # Auto slideshow mode
  autoslideHoverStop: 'true'                # Pause auto slideshow mode on mouseover
  interval: '4000'                          # The interval between each slide (Interval in millisecond)
  loop: 'true'                              # Infinite slideshow
  transition : zoom                         # Set the animation kind (fade/slide/page/zoom)
  itemsForSlide: '0'                        # Wrap each 'n' item
  touch: 'true'                             # Set a native slide for touch device
  swipe : 'true'                            # Enable swipe for touch device

footer:
    description: "Java base network management platform developed under the Open Source model."
    contact_title: "Contact Info"
    links_title: "Quick Links"
    copyright_text: "Copyright 2016 The OpenNMS Group, Inc. All Rights Reserved."
    feedburner: ""   # Your feedburner id for Newsletter footer modul


